### ISSUE TITLE
Unprocessed items with BatchWrite

### ISSUE THREAD

**Issue by youjinp** [a-h/ddbimport#1]
I've had almost 1 unprocessed item for every batch write, and retrying for unprocessed items significantly slows down the upload.

I wonder if you experience this too?

**Comment by a-h** [comment]
Yes, some throttling is inevitable.

<img width="1253" alt="Screenshot 2020-06-01 at 14 28 00" src="https://user-images.githubusercontent.com/1029947/83413658-1b260880-a414-11ea-8449-21fc8bc56f8e.png">

But overall, the effect is a high throughput.

<img width="350" alt="Screenshot 2020-05-05 at 14 40 27" src="https://user-images.githubusercontent.com/1029947/83413596-05b0de80-a414-11ea-8f50-b91ba6b1fcec.png">

**Comment by a-h** [comment]
I'm not sure about the "unprocessed item" though, that doesn't sound correct.

**Comment by a-h** [comment]
Hi, just to follow up, there's a great article from Yan Cui on this. It describes a strategy for setting up DynamoDB tables to get the maximum capacity straight away: https://theburningmonk.com/2019/03/understanding-the-scaling-behaviour-of-dynamodb-ondemand-tables/

**Comment by youjinp** [comment]
Very insightful. Thanks for that!

**Comment by N3RG4L** [comment]
Dynamodb now supports warm throughput
