### ISSUE TITLE
preflight batch generation error

### ISSUE THREAD

**Issue by hurleyLi** [a-h/ddbimport#5]
Thanks so much for creating this workflow! I'm able to import 60M rows in <30min!  

 except for a minor issue during the preflight stage, where the first batch is always from 0 to the end of the file. For instance:

```
"prefl": {
    "l": 59515375,
    "o": 2123819562,
    "cnt": false,
    "cols": [
        ......
    ]
  },
  "batches": [
    [
      0,
      2123819562
    ],
    [
      0,
      3532055
    ],
    [
      3532055,
      7135322
    ],
    [
      7135322,
      11102186
    ], ..........
```
you can see the first batch array is essentially the whole file [0, 2123819562]. I found this error because the first job hits the 15min lambda limit. 

I've not familiar with Golang, but I suspect the error is generated from this pull request #3 
```
resp.Batches = append(resp.Batches, []int64{batchStartIndex, srcSize})
```
I think this line adds the whole file as a single batch on the initial preflight (although it does solve the problem of lines not multiple of 100k rows). I could be wrong though, since I don't know about Golang....

**Comment by a-h** [comment]
Thanks, you're absolutely right, that line of code is suspect. The `batchStartIndex` hasn't actually been moved from zero at that point, it only happens later. I'll refactor that code to make it more testable and flush out that bug.

**Comment by a-h** [comment]
Hi @hurleyLi, I've updated the code after a refactor to make it easier to test the batching in isolation. Hopefully the tests are easy enough to read, so you can see what's going on. If you could give it a real-world test and verify that it's working for you, that would be great.

**Comment by hurleyLi** [comment]
__Tested and worked well! For files < 100k, >100k, and files not multiple by 100k lines, all worked! Thanks!!!__
Just want to clarify, could you please confirm that does each preflight job generated multiple batches, for example
```
    [
      0,
      3532055
    ],
    [
      3532055,
      7135322
    ],
    [
      7135322,
      11102186
    ]
```
at one single job, until it runs out of time if the file is too big to trigger another one?

(as opposed to each preflight job generated one batch number, e.g. the first preflight job generated `[0, 3532055]` and launch the next one to generate `[3532055, 7135322]`)

**Comment by a-h** [comment]
I've added some unit tests that describe the behaviour.

Overall, a Step Function runs the process. The Step Function starts by running the preflight Lambda, which reads through the S3 file sequentially, counting the lines and outputting a start and end byte offset for each "batch" of 10k lines. You can see the batches under the `prefl.batches` JSON key.

It's possible that the preflight Lambda is unable to read through the complete file within the Lambda timeout. The preflight Lambda exits early if the timeout could be reached, but outputs where it got up to in the file (`l` is the number of lines and `o` is the current byte offset).

The preflight Lambda also outputs `cnt` (continue) as `true` if it didn't manage to process the whole file. This instructs the Step Function to _continue_ to read through the file by running the preflight Lambda again. AWS S3 has a byte range capability which allows the preflight Lambda to skip past data it already read.

Once `cnt` is set to false, the Step Function starts running parallel Lambda functions to import the byte ranges into DynamoDB.

**Comment by hurleyLi** [comment]
Thanks so much for the clarification!!
